baseURL: "https://www.gesuindia.com/"
title: Gesu India
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    # main:
    #     - name: CV
    #       url: books/
    #       weight: 5 
    #     - name: Papers
    #       url: papers/
    #       weight: 2
    #     - name: Courses
    #       url: courses/
    #       weight: 3
    #     - name: Data
    #       url: data/
    #       weight: 4 
    #     - name: Blog
    #       url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
    #       weight: 6

params:
    description: ""
    author: Gesu India
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gesu India
          subtitle: |
            Hello, I’m a computer science researcher interested in <b>Equitable AI</b>, <b>Human-Computer Interaction</b>, and <b>Accessibility</b>. 
            Currently, I’m in my final year of a PhD in Computer Science at <a href="https://www.swansea.ac.uk/computational-foundry/">Computational Foundry</a>, Swansea University. 
            I work with my fantastic advisors: Dr. <u><a href="https://www.swansea.ac.uk/staff/computational-foundry/m.jones/">Matt Jones</a></u>, Dr. 
            <u><a href="https://www.swansea.ac.uk/staff/computational-foundry/s.robinson/">Simon Robinson</a></u>, Dr. <u><a href="https://www.swansea.ac.uk/staff/computational-foundry/j.pearson/">Jennifer Pearson</a></u>, and Dr. 
            <u><a href="https://www.microsoft.com/en-us/research/people/cmorri/">Cecily Morrison</a></u> (Microsoft Research, Cambridge). 
            My PhD thesis explores “disability-first approaches to AI dataset collection in low-resource communities,” 
            and is funded by <a href="https://epsrc.ukri.org/">EPSRC</a> and <a href="https://www.microsoft.com/en-us/research/">Microsoft Research, Cambridge</a>. 
            I’m always excited to discuss new ideas (and currently exploring full-time roles!), so feel free to reach out if you'd like to chat about my work.
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv.pdf
              #   "https://drive.google.com/file/d/1WB0IBcVUXzPJRGtC3kWmf0EUBUJ2ij7A/view?usp=sharing"
              # params:
              # external: true
          # buttons:
          #   - name: CV
          #     url: cv.pdf
          #   - name: Courses
          #     url: courses/
          #   - name: Data
          #     url: data/
          #   - name: Books
          #     url: books/
          #   - name: Tags
          #     url: tags/
          #   - name: Archive
          #     url: archive/
          #   - name: Blog
          #     url: 
    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:gesu.india@swansea.ac.uk
        # - name: Zoom
        #   url: 
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=kdl-wLoAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/gesuindia
        # - name: Substack
        #   url: 
        # - name: YouTube
        #   url: 
        - name: Twitter
          url: https://x.com/GesuIndia

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gesu India"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2