baseURL: "https://www.gesuindia.com/"
title: Gesu India
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: ""
    author: Gesu India
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gesu India
          subtitle: |
                  Hey there! I'm a computer science researcher passionate about <u>Equitable AI</u>, <u>Human-computer Interaction</u>, and <u>Accessibility</u>. Right now, I'm soon completing my PhD at <a href="https://www.swansea.ac.uk/computational-foundry/" target="_blank">Computational Foundry, Swansea Uni</a>, with the support of my amazing supervisors: 
                  <a href="https://www.swansea.ac.uk/staff/matt.jones/" target="_blank">Dr. Matt Jones</a>, 
                  <a href="https://www.swansea.ac.uk/staff/s.n.w.robinson/" target="_blank">Dr. Simon Robinson</a>, 
                  <a href="https://www.swansea.ac.uk/staff/j.pearson/" target="_blank">Dr. Jennifer Pearson</a>, and 
                  <a href="https://www.microsoft.com/en-us/research/people/cecilym/" target="_blank">Dr. Cecily Morrison</a>.
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: 
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:gesuindia@gmail.com
        - name: Zoom
          url: 
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: 
        - name: GitHub
          url: https://github.com/gesuindia
        - name: Substack
          url: 
        - name: YouTube
          url: 
        - name: Twitter
          url: 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gesu India"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2