baseURL: "https://www.gesuindia.com/"
title: Gesu India
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

# Remove or update taxonomies if not needed
taxonomies:
    tag: tags

menu:
    # Uncomment or update main menu items if needed, for example:
    # main:
    #     - name: CV
    #       url: cv/
    #       weight: 5 

params:
    description: ""
    author: Gesu India
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gesu India
          subtitle: |
            Hello, I’m a computer science researcher interested in <b>Equitable AI</b>, <b>Human-Computer Interaction</b>, and <b>Accessibility</b>. 
            Currently, I’m in my final year of a PhD in Computer Science at <a href="https://www.swansea.ac.uk/computational-foundry/">Computational Foundry</a>, Swansea University, 
            with my fantastic supervisors— <a href="https://www.swansea.ac.uk/staff/matt.jones/"><u>Dr. Matt Jones</u></a>, 
            <a href="https://www.swansea.ac.uk/staff/s.n.w.robinson/"><u>Dr. Simon Robinson</u></a>, <a href="https://www.swansea.ac.uk/staff/j.pearson/"><u>Dr. Jennifer Pearson</u></a>, and 
            <a href="https://www.microsoft.com/en-us/research/people/cecilym/"><u>Dr. Cecily Morrison</u></a> (Microsoft Research, Cambridge). 
            My research focuses on <i>“disability-first approaches to AI dataset collection in low-resource communities,”</i> funded by <a href="https://epsrc.ukri.org/">EPSRC</a> and <a href="https://www.microsoft.com/en-us/research/">Microsoft Research, Cambridge</a>. 
            If you’d like to chat about my work, feel free to reach out—I’m always excited about new ideas! <br><br>
            <b>I’m also on the job market starting May 2025 and would love to hear from you if you have any full-time roles available!</b>

          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv.pdf
    socialIcons:
        - name: Email
          url: mailto:gesu.india@swansea.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=kdl-wLoAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/gesuindia
        - name: Twitter
          url: https://x.com/GesuIndia

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gesu India"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
